FROM reg-online.yhroot.com/satop/node:12.16.1p
## 项目根目录
ARG appname=$appname
ARG dpenv=$dpenv
ARG apphome=/yinhe/apps/$appname
ARG applog=/yinhe/logs/$appname
ARG ENV=$ENV
USER root
WORKDIR $apphome
RUN useradd -m -d $apphome -u 1000 yinhe
COPY . .
COPY apps_config /yinhe/apps/config/$appname/
RUN  mkdir -p $applog && chown -R yinhe:yinhe /yinhe  && chmod +x ./scripts/build-tool.sh && chown -R yinhe:yinhe /yinhe/apps/config/$appname/
USER yinhe
ENV NODE_ENV=prod
ENV APPNAME=$appname
ENV TZ='Asia/Shanghai'
EXPOSE 2020
ENTRYPOINT ["./scripts/build-tool.sh","start", "prod"]
